service: aws-nodejs 

custom:
  region: 'us-east-1'
  dynamodb: 'pizzerias'

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    YELP_API_KEY: ${opt:yelp}
    DYNAMODB_TABLE: ${self:custom.dynamodb}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:ListTable
        - dynamodb:CreateTable
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  getPizzerias:
    role: CloudwatchEvent_Lambda
    handler: handler.getPizzerias

# resources:
#   Resources:
#     MyEventName:
#       Type: AWS::Events::Rule
#       Properties:
#         Description: Scrape pizzerias from yelp
#         Name: YelpPizzaScrape
#         ScheduleExpression: "cron(0 0 * * *)"
#         State: ENABLED
#         RoleArn:
#           Fn:GetAtt: 
#             - "CloudwatchEvent_Lambda"
#             - "Arn"
#         Targets:
#           -
#             Arn:
#               Fn::GetAtt:
#                 - "getPizzerias"
#                 - "Arn"
#               Id: "getPizzerias"
    